// <auto-generated />
using FuelConsumptionApp.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelConsumptionApp.Infra.Data.Migrations
{
    [DbContext(typeof(DefaultDbContext))]
    [Migration("20230520060204_AddColumnRefueledLitersAtFuelConsumptionTable")]
    partial class AddColumnRefueledLitersAtFuelConsumptionTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("FuelConsumptionApp.Entities.FuelConsumption", b =>
                {
                    b.Property<int>("SerialNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnOrder(3);

                    b.Property<int>("RefueledLiters")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.HasKey("SerialNumber");

                    b.ToTable("FuelConsumption");
                });
#pragma warning restore 612, 618
        }
    }
}
